### ISSUE TITLE
Динамический config 

### ISSUE THREAD

**Issue by nononoy** [teachbase/amorail#13]
Есть n аккаунтов амо,  во все нужно писать события. Есть ли сейчас возможность обойтись без config, а задавать 

usermail: 'amorail@test.com'
api_key: '75742b166417fe32ae132282ce178cf6'
api_endpoint: 'https://test.amocrm.ru'

динамически.

**Comment by palkan** [comment]
Сейчас такой возможности, к сожалению, нет.
Подумаем, как это сделать.
