### ISSUE TITLE
There was an error while trying to load the gem 'amorail'     (rspec-test environment)

### ISSUE THREAD

**Issue by aarkerio** [teachbase/amorail#19]
I'm getting this error message:

RAILS_ENV=test bundle exec rspec spec/requests/home_applications_spec.rb -e "GET /score/"

/home/manuel/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'amorail'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Amorail::Lead

The Amorail:Lead is called from the **ops_lead.rb** file. Even if add "require 'amorail'" to the file  the code works fine on development and production but no when I try to run a test.

UPDATE

We can close this one. All was an error in my PATH.

**Comment by ivanovaleksey** [comment]
Hi @aarkerio, please close the issue.
