### ISSUE TITLE
Forgotten v.0.3.1 tag

### ISSUE THREAD

**Issue by ivanovaleksey** [teachbase/amorail#22]
Hi @palkan,

seems like you forgot to push 0.3.1 tag.
Or is it done intentionally?

**Comment by palkan** [comment]
Hi!

Intentionally. Version 0.3.1 is published on rubygems.

**Comment by ivanovaleksey** [comment]
Oh, thanks.
Yes, I saw 0.3.1 on rubygems.
I thought new version on rubygems is always a new tag in repository.
