### ISSUE TITLE
Find returns false

### ISSUE THREAD

**Issue by ivanovaleksey** [teachbase/amorail#25]
Hi @palkan,

Today I have faced with an issue: 
```
Amorail::Lead.find ANY_NONEXISTENT_ID
=> false
```

I don't it is convenient to return `false` from `#find` because one waits for lead instance (if given lead is exists) or `nil`.

It seems like it occurs because of `Entity#handle_response` [returns `false`](https://github.com/teachbase/amorail/blob/master/lib/amorail/entity.rb#L112).

My proposal is to return `nil` instead of `false`.

What do you think?

**Comment by palkan** [comment]
Yep, `nil` is better. Feel free to submit a PR.
