### ISSUE TITLE
Code 200 but errors in response

### ISSUE THREAD

**Issue by ivanovaleksey** [teachbase/amorail#27]
Hi @palkan,

recently I received a response with status 200 but there was errors inside
```
{"response"=>{"leads"=>{"update"=>{"errors"=>{"1572277"=>"Last modified date is older than in database"}}}, "server_time"=>1499868971}}
```

I just didn't specify `last_modified` attribute on update.

The problem is really tricky because one receives 200 (and Amorail treats it as a successful response) but object is not actually saved.

What do you think, can we deal with it somehow?

**Comment by palkan** [comment]
Interesting.

Currently, we assume that update always succeeds.

We can deal with it the following way:

- parse response object and check whether there is an "errors" key present (and non-empty) for every method

- add "errors" messages to our entity's `errors` (`errors.add(:base, msg)`)
 
- return `false` from [`handle_response`](https://github.com/teachbase/amorail/blob/master/lib/amorail/entity.rb#L111).

**Comment by ivanovaleksey** [comment]
Thanks @palkan, I will try to implement this behaviour.
