### ISSUE TITLE
Raw search method

### ISSUE THREAD

**Issue by ivanovaleksey** [teachbase/amorail#30]
Hi @palkan,

It is necessary sometimes to be able to find all entities using `limit_rows` and `limit_offset` or to search by [`type`](https://developers.amocrm.ru/rest_api/notes_list.php).

For now I use the following dirty solution:
```
Amorail::Lead.instance_eval do
  def list(params = {})
    response = client.safe_request(
      :get,
      remote_url('list'),
      **params
    )
    load_many(response)
  end
end
```

I would like to have a method with similar functionality out of the box.
We can name some more AR-like, for instance, `where`.

What do you think?

**Comment by palkan** [comment]
Hey, Alex!

Check this out #31

**Comment by ivanovaleksey** [comment]
@palkan awesome!
