### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by illustrarium** [teachbase/amorail#34]
Привет, настроил отправку новых записей из приложения в АМО, на локальной машине все работает и напрямую и через воркер, на продакшн сервере выдает ошибку

```ruby
undefined method `+' for nil:NilClass
```

вот сам код 
```ruby
contact = AmoContact.new(
        name: @customer.name + " " + @customer.surname,
        phone: @customer.phone,
        bday: @customer.bday,
        address: @customer.address
      )
      contact.save!
```

Вот эта строчка не при чем:
```ruby
name: @customer.name + " " + @customer.surname,
```
в переменных тоже 100% есть данные, вот хеш с параметрами с той же страницы, что и ошибка
```
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"jCgmFBsn2GBK/uq+GbkOPztzExIlcq/qtxmtvg7tTBn0e57pu2V+NvlUBVZ655ZXdV2l16LV1nRL0YlzffufBw==",
 "customer"=>{"name"=>"Aleksey", "surname"=>"Paschenko", "phone"=>"********", "address"=>"Bogatyrova", "job"=>"", "diler"=>"0", "bday"=>"26.07.2017", "note"=>""},
 "commit"=>"Create Customer"}
```

ругается на `contact.save!`

**Comment by ivanovaleksey** [comment]
@illustrarium привет, покажи backtrace ошибки.

**Comment by illustrarium** [comment]
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1570:in `addr_port'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1503:in `begin_transport'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1442:in `transport_request'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1416:in `request'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:877:in `start'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
faraday (0.12.1) lib/faraday/adapter/net_http.rb:78:in `perform_request'
faraday (0.12.1) lib/faraday/adapter/net_http.rb:38:in `block in call'
faraday (0.12.1) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
faraday (0.12.1) lib/faraday/adapter/net_http.rb:33:in `call'
faraday (0.12.1) lib/faraday/rack_builder.rb:139:in `build_response'
faraday (0.12.1) lib/faraday/connection.rb:386:in `run_request'
faraday (0.12.1) lib/faraday/connection.rb:149:in `get'
amorail (0.3.3) lib/amorail/client.rb:51:in `get'
amorail (0.3.3) lib/amorail/client.rb:44:in `safe_request'
amorail (0.3.3) lib/amorail/property.rb:64:in `load_fields'
amorail (0.3.3) lib/amorail/property.rb:59:in `reload'
amorail (0.3.3) lib/amorail/property.rb:55:in `initialize'
amorail (0.3.3) lib/amorail/client.rb:25:in `new'
amorail (0.3.3) lib/amorail/client.rb:25:in `properties'
amorail (0.3.3) lib/amorail.rb:18:in `properties'
amorail (0.3.3) lib/amorail/entity.rb:57:in `properties'
amorail (0.3.3) lib/amorail/entity/params.rb:11:in `params'
amorail (0.3.3) lib/amorail/entity/params.rb:37:in `create_params'
amorail (0.3.3) lib/amorail/entity.rb:99:in `push'
amorail (0.3.3) lib/amorail/entity/persistance.rb:16:in `save'
amorail (0.3.3) lib/amorail/entity/persistance.rb:20:in `save!'
app/controllers/customers_controller.rb:30:in `block in create'
actionpack (5.0.4) lib/action_controller/metal/mime_responds.rb:195:in `respond_to'
app/controllers/customers_controller.rb:21:in `create'
actionpack (5.0.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.4) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.4) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.4) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.4) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.4) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.4) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.4) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.4) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.4) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.4) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.4) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.4) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.4) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.4) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.4) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.4) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.4) lib/action_dispatch/routing/route_set.rb:725:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.4) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.4) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.4) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.4) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.4) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.4) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.4) lib/rails/engine.rb:522:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by ivanovaleksey** [comment]
@illustrarium с конфигами на продакшн все нормально?

**Comment by illustrarium** [comment]
@ivanovaleksey простите дурака, secrets.yml недозаполнил, можно закрывать

**Comment by ivanovaleksey** [comment]
@illustrarium у меня прав нет ☺️ 
можешь закрыть сам на правах создателя 😃

**Comment by greenclaw** [comment]
У меня возникла аналогичная ошибка только при создании Lead. Создаю lead с кастомным полем, единственный момент, поле почему то из амо приходит транслитом `Сообщение`. Метод контроллера:
```
def contacts_submit
    @contact = Contact.create(contact_params)

    amo_lead = Lead.new(
      name:  "Покупка машины",
      tags: "Спецтехника",
      status_id: "11975518"
    )
    amo_lead.Сообщение = contact_params[:message]
    amo_lead.save!
    # sleep 1.5

    possible_contact =  Amorail::Contact.find_by_query("#{contact_params[:phone]} #{contact_params[:email]}").first
    if possible_contact
      possible_contact.update(name: contact_params[:name],
         phone: contact_params[:phone],
         email: contact_params[:email],
         company_name: contact_params[:company]
      )
      possible_contact.linked_leads_id << amo_lead.id
      possible_contact.save!
    else
      amo_contact = Amorail::Contact.new(
        name: contact_params[:name],
        company_name: contact_params[:company],
        phone: contact_params[:phone],
        email: contact_params[:email]
      )
      amo_contact.linked_leads_id << amo_lead.id
      amo_contact.save!
    end
    

    respond_to do |format|
      format.js
      format.html { redirect_to contacts_path }
    end
  end
```
Модель:
```
class Lead < Amorail::Lead
  amo_property :Сообщение
end
```
Все работает локально, заявка приходит с контактом, но когда тестирую на сервере в продакшн среде, вылетает ошибка.
В логах:
```
I, [2018-03-07T16:25:59.766297 #4390]  INFO -- : [b7b7f6c7-f7e8-43c2-bf64-6ca06cee1f85] Completed 500 Internal Server Error in 130ms (ActiveRecord: 18.2ms)
F, [2018-03-07T16:25:59.767487 #4390] FATAL -- : [b7b7f6c7-f7e8-43c2-bf64-6ca06cee1f85]
F, [2018-03-07T16:25:59.767575 #4390] FATAL -- : [b7b7f6c7-f7e8-43c2-bf64-6ca06cee1f85] NoMethodError (undefined method `+' for nil:NilClass):
F, [2018-03-07T16:25:59.767611 #4390] FATAL -- : [b7b7f6c7-f7e8-43c2-bf64-6ca06cee1f85]
F, [2018-03-07T16:25:59.767647 #4390] FATAL -- : [b7b7f6c7-f7e8-43c2-bf64-6ca06cee1f85] app/controllers/pages_controller.rb:27:in `contacts_submit'
I, [2018-03-07T16:26:59.869591 #4390]  INFO -- : [8d8ca8c4-4cbc-4589-80d2-b8acde663c6b] Started HEAD "/" for 63.143.42.245 at 2018-03-07 16:26:59 +0300
I, [2018-03-07T16:26:59.870809 #4390]  INFO -- : [8d8ca8c4-4cbc-4589-80d2-b8acde663c6b]
```

При этом, если создавать лид из консоли на сервере все работает.
В чем может быть проблема?

**Comment by ivanovaleksey** [comment]
@greenclaw если из консоли работает, то, может быть, процесс приложения запущен не с тем конфигом? Может быть, перезапуск поможет.
