### ISSUE TITLE
Создание custom_fields

### ISSUE THREAD

**Issue by vitalykorneev** [teachbase/amorail#39]
Привет! Подскажите пожалуйста, как отправлять кастомные поля при создании lead?
Мой пример не работает(
Если не указывать поле **custom_fields** все работает отлично. 
У моего поля тип "Текст".
```
lead = Amorail::Lead.new(
  name:  "Example Lead",
  tags: "IT, Sales",
  price: 100,
  status_id: Amorail.properties.leads.statuses[
    Rails.application.secrets.amoparams['lead_status']
  ].id,
  custom_fields: [{
    :id => '1778775',
    :values => ['test']
  }]
)

lead.save!
```

**Comment by ivanovaleksey** [comment]
Привет. 
Можно сделать свой класс и прописать в нем _custom_fields_, используя `amo_property`.

```
class Lead < Amorail::Lead
  amo_property :foo
end

lead = Lead.new
lead.name = "..."
...
lead.foo = "bar"
lead.save!
```

**Comment by vitalykorneev** [comment]
Спасибо, это помогло.
Подскажите, каким лучшим образом можно добавить кастомное поле на русском языке?
Сейчас я делаю это так:
```
class MyAmoLead < Amorail::Lead
  amo_property 'поле'
end

lead.поле = 'значение'
lead.save!
```
Мне кажется такой вариант не очень изящным. Смущает имя поля написанное кириллицей.

**Comment by ivanovaleksey** [comment]
На данный момент, наверное, можно только так.
Есть форк, в котором сделана поддержка русскоязычных полей (но форк не обновлен до последней версии основного репозитория): https://github.com/foxford/amorail

Там можно задать имя метода
```
amo_property 'поле', method_name: :my_field
```

Возможно, со временем добавится что-то подобное и в этот проект.

**Comment by vitalykorneev** [comment]
Спасибо!

**Comment by SergejOvsiannikov** [comment]
@ivanovaleksey, добрый день!

А что делать, если поля мало того, что на кириллице, так еще и названы ужасным образом.
Например, у меня есть поле `Ко-во- участников`

При записи вида
```
class AmoLead < Amorail::Lead
  amo_property 'Ко-во- участников'
end
```

я получаю ошибку
`NameError: invalid attribute name 'Ко-во- участников'`

Почему нельзя параметром указать привязку по id кастомного аттрибута, это было бы очень удобно.

Что-то вроде:
`amo_property :any_attr_name, id: 12412`

Спасибо.

**Comment by greenclaw** [comment]
Попробовал сделать custom_fields по инструкции выше, создал модель с полем, не сработало. 
```
class Lead < Amorail::Lead
  amo_property :message
end
```
Получил следующую ошибку при сохранении:
`NoMethodError: undefined method 'message' for #<Amorail::Property::Lead:0x007f965f4a1a08> 
from /Users/rvarnava/.rvm/gems/ruby-2.3.3/gems/amorail-0.4.0/lib/amorail/property.rb:8:in 'method_missing'`

**Comment by ivanovaleksey** [comment]
@greenclaw а свойство `message` существует?
Проверьте `custom_fields` через `rake amorail:check`.

**Comment by greenclaw** [comment]
@ivanovaleksey проблема была в том, что поле называлось `Сообщение`, прописал в модели такое же название, все заработало.

Спасибо!

**Comment by arsensokolov** [comment]
Не могу понять в чем проблема, чтобы я не написал, все равно ошибка:

    NoMethodError (undefined method `url123' for #<Amorail::Property::Lead:0x007ffc07ba8a50>):

**Comment by ivanovaleksey** [comment]
@ArsenBespalov судя по ошибке вы используете `Amorail::Property::Lead`.
Это класс из библиотеки, там, конечно, нет метода `url123`.
В примерах выше создается дочерний класс
```ruby
class Lead < Amorail::Lead
  # здесь объявление ваших свойств
end
```

**Comment by arsensokolov** [comment]
@ivanovaleksey именно так и делал, но именно на строку `amo_property :url123` он как раз и жалуется, не понимаю в чем проблема, у всех все хорошо, может я что-то не так делаю?

Данное поле точно существует в amoCRM.

**Comment by ivanovaleksey** [comment]
@ArsenBespalov мой предыдущий коммент, скорее всего, некорректный - перепутал `Amorail::Property::Lead` c `Amorail::Lead`.
Могу только посоветовать проверить используемую версию гема и проверить, что возвращает API через `rake amorail:check`.
Например, @greenclaw [это помогло](https://github.com/teachbase/amorail/issues/39#issuecomment-365612794).

**Comment by arsensokolov** [comment]
@ivanovaleksey, спасибо за оперативность.

Сейчас протестировал дома, на другом компьютере и все заработало как было написано, не понимаю почему на работе не работало, странная ситуация.

Только не понимаю, возможно ли как заполнять поля с русскими надписями?

**Comment by ivanovaleksey** [comment]
@ArsenBespalov явно какие-то проблемы с версиями, не забывайте добавлять `bundle exec`.
Про русские буквы почитайте [тред](https://github.com/teachbase/amorail/issues/39#issuecomment-328058145) внимательнее, думаю, это отвечает на вопрос.

**Comment by arsensokolov** [comment]
@ivanovaleksey выходит ради поддержки русских полей придется отказаться от последних обновлений?

**Comment by ivanovaleksey** [comment]
@ArsenBespalov, если такая функциональность нужна, то можно добавить это в текущий проект.
Можете попробовать поработать над этим, реализацию взять из указанного форка или придумать что-то другое.

**Comment by ArsenBespalov** [comment]
@ivanovaleksey я понял в чем проблема, оказывается не работает на Ruby ~> 2.5.0.

**Comment by me-kirill** [comment]
Хорошо бы добавить в документацию что в amo_property нужно передавать название строчными буквами.

**Comment by palkan** [comment]
> Хорошо бы добавить в документацию что в amo_property нужно передавать название строчными буквами.

Идея хорошая. Не хотите сделать pull request?
