### ISSUE TITLE
Будет ли поддержка новой версии API?

### ISSUE THREAD

**Issue by arsensokolov** [teachbase/amorail#41]
Сейчас уже не открывается старая документация, пока что еще осталась [английская версия](https://developers.amocrm.com/rest_api/), хоть на этом спасибо, но вот с русской проблема.

**Comment by ivanovaleksey** [comment]
@ArsenBespalov, к сожалению, я не готов взяться за работу над поддержкой новой версии, так как сейчас не связан с amoCRM по работе, а свободного времени на это нет.
Возможно, кто-то сможет заняться этим и прислать пулл реквест.
