### ISSUE TITLE
Не работает обновление сделки

### ISSUE THREAD

**Issue by tit** [teachbase/amorail#42]
Нахожу сделку.
```ruby
lead = Amorail::Lead.find LEAD_ID
```
Хочу поменять два параметра (`responsible_user_id` и `status_id`).
Пытаюсь это сделать двумя способами.
Оба способа падают с ошибками.
```ruby
lead.update! responsible_user_id: MANAGER_ID, status_id: STATUS_ID
#=> Amorail::Entity::NotPersisted: Amorail::Entity::NotPersisted

# or

lead.responsible_user_id = MANAGER_ID
lead.status_id = STATUS_ID
lead.save!
#=> Amorail::Entity::InvalidRecord: Amorail::Entity::InvalidRecord
```

В какую сторону смотреть?

**Comment by palkan** [comment]
`update!` работает только у уже сохраненными объектами (поэтому и ошибка `NotPersisted`).

во втором случае не проходит валидация на стороне модели, можно посмотреть в `lead.errors.messages`, чего именно не хватает; у Lead должно быть обязательно задано поле `name`, возможно, в этом дело

**Comment by tit** [comment]
> не проходит валидация на стороне модели, можно посмотреть в lead.errors.messages

Спасибо за совет про `lead.errors.messages`, не знал.
Смотрю туда после ошибки.

```irb
2.4.1 :012 > lead = Amorail::Lead.find 34249340
 => #<Amorail::Lead:0x007fb3b62d4c88 @last_modified=1536269026, @id="1202089", @name="Сейф", @date_create=1535714040, @price="0", @responsible_user_id="76026", @pipeline_id=82590, @tags=[], @status_id="143"> 
2.4.1 :013 > lead.responsible_user_id = AmoCRM::MANAGER_YULIYA_STOLYAROVA
 => 187886 
2.4.1 :014 > lead.status_id = AmoCRM::LEAD_STATUS_IN_PROGRESS
 => 4854614 
2.4.1 :015 > lead.save
 => false 
2.4.1 :016 > lead.errors.messages
 => {:base=>["Lead not found"]} 
```

Странная ошибка `{:base=>["Lead not found"]} `.
Как lead может быть не найден, если он найден в самом начале?

**Comment by palkan** [comment]
Странно, что id не совпадает

> 2.4.1 :012 > lead = Amorail::Lead.find 34249340
 => #<Amorail::Lead:0x007fb3b62d4c88 @last_modified=1536269026, @id="1202089" ...

Ищем по одному, а в ответе другой id приходит. 

Хорошо бы увидеть логи HTTP запросов. Можно через [`sniffer`](https://github.com/aderyabin/sniffer) посмотреть

**Comment by tit** [comment]
@palkan, ещё раз большое спасибо.
Кажется, я разобрался.
Главное — у меня вроде заработало всё.
В нашей системе мы добавили кастомное поле в сделку с именем id (знаю, что глупо).

Ещё раз.
В нашей системе есть сущность order, которая имеет id.
При создании такой сущности мы создаём сделку в AmoCRM, где AmoCRM сделке присваивает собственный «инкрементальный» id.
Должны добавлять поле order_id, а добавляем просто id. Ну вот так. :)
Когда я делаю Amorail::Lead.find amocrm_lead_id, то Amorail находит мне нужную сделку с правильным amocrm_lead_id, но заполняет переменную `@id` значением кастомного поля id, т. е. по факту order_id.
Наример, в нашей системе мы создали сущность order_id: 42, а AmoCRM присвоило новой сделке amocrm_lead_id: 100500.
Я делаю lead = Amorail::Lead.find 100500, и получаю нужный объект со сделкой 100500, в которой стоит Amorail::Lead:0x007f868714ede8 @id=42.
Соответственно, при попытке сохранить такую сделку AmoCRM ругается, что lead с id: 42 не найден.

Решил это путём переприсвоения переменной @id значения amocrm_lead_id.

```ruby
2.4.1 :017 > lead = Amorail::Lead.find amocrm_lead_id
 => #<Amorail::Lead:0x007f868714ede8 @id="1202089", @status_id="143", @last_modified=1536312135, @name="Сейф", @date_create=1535714040, @price="0", @responsible_user_id="76026", @pipeline_id=82590, @tags=[{"id"=>267590, "name"=>"тест", "element_type"=>2}]> 
2.4.1 :018 > lead.status_id = AmoCRM::LEAD_STATUS_IN_PROGRESS
 => 4854614 
2.4.1 :019 > lead.id = amocrm_lead_id
 => 34249340 
2.4.1 :020 > lead.save
 => #<Amorail::Lead:0x007f868714ede8 @id=34249340, @status_id=4854614
```

Всё заработало. Ещё раз спасибо!
