### ISSUE TITLE
Реализации oAuth

### ISSUE THREAD

**Issue by lHydra** [teachbase/amorail#48]
Они сейчас поменяли систему авторизации на oAuth, я хочу реализовать в геме [упрощенный вариант](https://www.amocrm.ru/developers/content/oauth/easy-auth), думаю как лучше сделать, сейчас сохраняю `access_token` и `refresh_token` в файл, затем проверяем не протух ли токен и в случае надобности - обновляем его. Но думаю может лучше добавить настройку и например, связывать гем с базой приложения, и коды напрямую записывать туда?

**Comment by palkan** [comment]
> Но думаю может лучше добавить настройку и например, связывать гем с базой приложения, и коды напрямую записывать туда?

В идеале бы абстрагировать хранилище, чтобы разработчики могли сами выбрать способ.
Примерно такой API:

```ruby
Amorail.tokens_store = MyStore.new

class MyStore
  def exists?(key)
  end

  def read(key)
  end

  def write(key, val)
  end
end
```

По умолчанию можно реализовать просто хранение в памяти.

См., например, https://github.com/tuwukee/jwt_sessions/pull/39
