### ISSUE TITLE
По документации тянется неактуальная версия гема

### ISSUE THREAD

**Issue by Seintero** [teachbase/amorail#52]
Добрый день, возможно вы забыли добавить тег на свежую версию) Пробовали с коллегой стягивать гем и он был без авторизации oauth, версия шла 0.6.1. Стянулось свежее, только когда гвоздями ветку master прописала.

**Comment by AlexanderShvaykin** [comment]
Добрый день. Да забыли 😄 Вскоре опубликую на rubygems

**Comment by AlexanderShvaykin** [comment]
опубликована новая версия в rubygems

**Comment by Seintero** [comment]
> опубликована новая версия в rubygems

Спасибо :)
